[programs.devnet]
guess5_escrow = "3ZvWJs6FY47rUbnpdmKgAcFVLUhCETvwG7HS1xV2Torn"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 