[programs.devnet]
guess5 = "bmUnEvC6W4JDLG6vdqbTJX73wECTeUZAWgptmNuabd1"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 