[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
guess5_escrow = "HyejroGJD3TDPHzmCmtUSnsViENuPn6vHDPZZHw35fGC"

[programs.mainnet]
guess5_escrow = "BnATdNCmijkHo74t76djNNDqfUyzSacvrEbG94KFSVux"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
